routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('front.index');
});


Route::group(['namespace'=>'Web\Admin'] , function (){
    Route::get('panel' , 'PanelController@index')->name('admin.panel');
    Route::post('sort' , 'CategoryController@sort')->name('sort.ajax');
    Route::post('sortSubCategory' , 'CategoryController@sortSubCategory')->name('sortSubCategory.ajax');
    Route::resource('categories' , 'CategoryController');
    Route::post('deleteCat' , 'CategoryController@deleteCat')->name('deleteCat.ajax');

});
Route::group(['namespace'=>'Front'] , function (){
    Route::get('/' , 'CategoryController@index');
    //Route::get('subCat/{id}' , 'CategoryController@show')->name('subCat');
    Route::resource('subCategories' , 'CategoryController');
});



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/Api/v1/CategoryController.php
<?php

namespace App\Http\Controllers\Api\v1;

use App\Http\Controllers\Controller;
use App\Services\Category\CategoryService;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    protected $categoryService;
    public function __construct()
    {
        $this->categoryService = new CategoryService();
    }
    public function insertValedCategory(Request $request)
    {
        $category = $this->categoryService->storeCategory($request->name , $request->subCategory_id , $request->icon, $request->img , $request->color);
        return $category;
    }
    public function getAllCategories()
    {
        $categories = $this->categoryService->getCategories();
        return $categories;
    }
}

app/Http/Controllers/Front/CategoryController.php
<?php

namespace App\Http\Controllers\Front;

use App\Category;
use App\Http\Controllers\Controller;
use App\Services\Category\CategoryService;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    protected $categoryService;
    public function __construct()
    {
        $this->categoryService = new CategoryService();
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = $this->categoryService->getCategories();
        return view('front.index' , compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category , $id)
    {
        $category = Category::find($id);
        $subCategories = $this->categoryService->getListSubCategoriess($id);
        return view('front.subCat' , compact('subCategories' , 'category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //
    }

}

app/Http/Controllers/Web/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use App\Category;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Category\SendRequest;
use App\Services\Category\CategoryService;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    protected $categoryService;
    public function __construct()
    {
        $this->categoryService = new CategoryService();
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $categories = $this->categoryService->getCategories();
        //return $categories;
        return view('Admin.category.index' , compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = $this->categoryService->getCategories();
        return view('Admin.category.create' , compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SendRequest $request)
    {
        $name = $request->name;
        $subCategory_id = $request->subCategory_id;
        $icon = $request->icon;
        $color = $request->color;
        if ($request->has('img')){
            $img = $request->img;
        }else{
            $img = null;
        }

        $this->categoryService->storeCategory($name , $subCategory_id , $icon , $img , $color);
        alert()->success('دسته بندی با موفقیت به ثبت رسیده است');
        return redirect(route('categories.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {

        $subCategories = $this->categoryService->getListSubCategories($category);
        return view('Admin.category.subCategory' , compact('subCategories' , 'category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $categories = $this->categoryService->getCategories();
        return view('Admin.category.edit' , compact('category' , 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(SendRequest $request, Category $category)
    {
        $name = $request->name;
        $subCategory_id = $request->subCategory_id;
        $icon = $request->icon;
        $color = $request->color;
        if ($request->has('img')){
            $img = $request->img;
        }else{
            $img = null;
        }
        $this->categoryService->updateCategory($category , $name , $subCategory_id , $icon , $img , $color);
        alert()->success('دسته بندی با موفقیت به آپدیت شده است');
        return redirect(route('categories.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //
    }
    public function sort(Request $request)
    {
        $this->categoryService->sortCategory($request->order);
    }
    public function sortSubCategory(Request $request)
    {
        //return $request->catId;
        $this->categoryService->sortSubCategory($request->order , $request->catId);
    }
    public function deleteCat(Request $request)
    {
        $this->categoryService->deleteCat($request->id);
    }
}

resources/views/Admin/category/create.blade.php
@extends('Admin.master')

@section('style')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-colorpicker/2.5.1/css/bootstrap-colorpicker.min.css" rel="stylesheet">
@endsection

@section('content')
    <div class="container-fluid">
        <div class="block-header">
            <div class="row clearfix">
                <div class="col-md-6 col-sm-12">
                    <h1>اضافه کردن دسته بندی جدید</h1>
                </div>
            </div>
        </div>
        <div class="row clearfix">
            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                        <h2>ثبت دسته بندی</h2>
                        @include('Admin.errors.error')
                    </div>
                    <div class="body">
                        <form id="basic-form" method="post" action="{{ route('categories.store') }}" enctype="multipart/form-data" novalidate>
                            @csrf
                            <div class="form-group" style="width: 80%;">
                                <label>نام دسته بندی</label>
                                <input type="text" name="name" class="form-control" required>
                            </div>
                            <div class="form-group" style="width: 80%;">
                                <label>دسته بندی</label>
                                <select id="multiselect-color2" name="subCategory_id" class="form-control">
                                    <option></option>
                                    @foreach($categories as $category)
                                        <option value="{{$category->id}}">{{$category->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            {{--<div class="form-group" style="width: 80%;">--}}
                                {{--<label>ساب کتگوری</label>--}}
                                {{--<select id="multiselect-color2" name="subCategory_id" class="form-control">--}}
                                    {{--<option></option>--}}
                                {{--</select>--}}
                            {{--</div>--}}
                            <div class="form-group" style="width: 80%;">
                                <label>آیکن</label>
                                <input type="text" name="icon" class="form-control" required>
                            </div>
                            <div class="form-group" style="width: 80%;">
                                <label>عکس</label>
                                <input type="file" name="img" class="form-control" required>
                            </div>
                            <div class="form-group" style="width: 80%;">
                                <label>انتخاب رنگ</label>
                                <div id="cp2" class="input-group colorpicker colorpicker-component">
                                    <input type="text" name="color" value="#00AABB" class="form-control" />
                                    <span class="input-group-addon"><i></i></span>
                                </div>
                            </div>
                            <br>
                            <button type="submit" class="btn btn-primary">ثبت اطلاعات</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection

@section('script')

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-colorpicker/2.5.1/js/bootstrap-colorpicker.min.js"></script>
    <script src="{{asset('/assets/bundles/datatablescripts.bundle.js')}}"></script>
    <script src="{{asset('/assets/bundles/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('/assets/bundles/buttons.bootstrap4.min.js')}}"></script>
    <script src="{{asset('/assets/bundles/buttons.colVis.min.js')}}"></script>
    <script src="{{asset('/assets/bundles/buttons.html5.min.js')}}"></script>
    <script src="{{asset('/assets/bundles/buttons.print.min.js')}}"></script>
    <script src="{{asset('/assets/bundles/bundles/mainscripts.bundle.js')}}"></script>
    <script src="{{asset('/assets/bundles/jquery-datatable.js')}}"></script>
    <script src="{{asset('/js/sweetalert.min.js')}}"></script>
    @include('sweet::alert')

    <script>
        $('.colorpicker').colorpicker({});
    </script>
@endsection

resources/views/Admin/category/edit.blade.php
@extends('Admin.master')

@section('style')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-colorpicker/2.5.1/css/bootstrap-colorpicker.min.css" rel="stylesheet">
@endsection

@section('content')
    <div class="container-fluid">
        <div class="block-header">
            <div class="row clearfix">
                <div class="col-md-6 col-sm-12">
                    <h1>اضافه کردن دسته بندی جدید</h1>
                </div>
            </div>
        </div>
        <div class="row clearfix">
            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                        <h2>ویرایش دسته بندی </h2>
                        @include('Admin.errors.error')
                    </div>
                    <div class="body">
                        <form id="basic-form" method="post" action="{{ route('categories.update' , $category->id) }}" enctype="multipart/form-data" novalidate>
                            @csrf
                            {{ method_field('PATCH') }}
                            <div class="form-group" style="width: 80%;">
                                <label>نام دسته بندی</label>
                                <input type="text" name="name" value="{{ $category->name }}" class="form-control" required>
                            </div>
                            <div class="form-group" style="width: 80%;">
                                <label>دسته بندی</label>
                                <select id="multiselect-color2" name="subCategory_id" class="form-control">
                                    <option></option>
                                    @foreach($categories as $category1)
                                        <option value="{{$category1->id}}" {{ $category->subCategory_id == $category1->id ? 'selected': ""  }}>{{$category1->name}}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group" style="width: 80%;">
                                <label>آیکن</label>
                                <input type="text" name="icon" value="{{ $category->icon }}" class="form-control" required>
                            </div>
                            <div class="form-group" style="width: 80%;">
                                <label>عکس</label>
                                <input type="file" name="img" class="form-control" required>
                            </div>
                            <div class="form-group" style="width: 80%;">
                                <label>انتخاب رنگ</label>
                                <div id="cp2" class="input-group colorpicker colorpicker-component">
                                    <input type="text" name="color" value="#00AABB" class="form-control" />
                                    <span class="input-group-addon"><i></i></span>
                                </div>
                            </div>
                            <br>
                            <button type="submit" class="btn btn-primary">ویرایش اطلاعات</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection

@section('script')

    <script src="{{asset('/assets/bundles/datatablescripts.bundle.js')}}"></script>
    <script src="{{asset('/assets/bundles/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('/assets/bundles/buttons.bootstrap4.min.js')}}"></script>
    <script src="{{asset('/assets/bundles/buttons.colVis.min.js')}}"></script>
    <script src="{{asset('/assets/bundles/buttons.html5.min.js')}}"></script>
    <script src="{{asset('/assets/bundles/buttons.print.min.js')}}"></script>
    <script src="{{asset('/assets/bundles/bundles/mainscripts.bundle.js')}}"></script>
    <script src="{{asset('/assets/bundles/jquery-datatable.js')}}"></script>
    <script src="{{asset('/js/sweetalert.min.js')}}"></script>
    @include('sweet::alert')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-colorpicker/2.5.1/js/bootstrap-colorpicker.min.js"></script>
    <script>
        $('.colorpicker').colorpicker({});
    </script>
@endsection

resources/views/Admin/category/index.blade.php
@extends('Admin.master')

@section('style')
    <link rel="stylesheet" href="{{asset('/assets/vendor/sweetalert/sweetalert.css')}}">
@endsection
@section('content')
    <div class="container-fluid">
        <div class="block-header">
            <div class="row clearfix">
                <div class="col-md-6 col-sm-12">
                    <h1>رنگ</h1>
                </div>
                <div class="col-md-6 col-sm-12 text-right hidden-xs">
                    <a href="{{ route('categories.create') }}" class="btn btn-sm btn-primary" title="">ایجاد دسته بندی</a>
                </div>
            </div>
        </div>

        <div class="row clearfix">
            <div class="col-lg-12">
                <div class="card">
                    <div class="header">
                        <h2>دسته بندی</h2>
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-hover js-basic-example dataTable table-custom spacing5" id="table">
                                <thead>
                                <tr>
                                    <th>ردیف</th>
                                    <th>نام</th>
                                    <th>آیکن</th>
                                    <th>رنگ</th>
                                    <th>عکس</th>
                                    <th>sort</th>
                                    <th>عملیات</th>
                                </tr>
                                </thead>
                                <tbody id="tablecontents">
                                @forelse ($categories as $index=>$value)
                                    <tr class="row1" data-id="{{ $value->id }}">
                                        <td>{{$index + 1}}</td>
                                        <td>{{$value->name}}</td>
                                        <td>{{$value->icon}}</td>
                                        <td>{{$value->color}}</td>
                                        <td>
                                            <img src="{{$value->img}}" class="img-fluid" width="100" height="100"/>
                                        </td>
                                        <td>{{$value->sort_order}}</td>
                                        <td>
                                            <button type="button" data-id="{{ $value->id }}" id="delete" class="btn btn-sm btn-danger" title="" data-toggle="tooltip" data-placement="top" data-original-title="حذف دسته بندی"><i class="icon-trash"></i></button>
                                            <a href="{{ route('categories.edit' , $value->id) }}" class="btn btn-sm btn-info" title="" data-toggle="tooltip" data-placement="top" data-original-title="ویرایش دسته بندی"><i class="icon-pencil"></i></a>
                                            <a href="{{ route('categories.show' , $value->id) }}" class="btn btn-sm btn-light" title="" data-toggle="tooltip" data-placement="top" data-original-title="نمایش دسته بندی"><i class="icon-eye"></i></a>
                                        </td>
                                    </tr>
                                @empty
                                    <p>No categories</p>
                                @endforelse
                                </tbody>
                            </table>
                            <h5>Refresh <button class="btn btn-default" onclick="window.location.reload()"><b>REFRESH</b></button></h5>

                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection

@section('script')
    {{--<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>--}}
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    {{--<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.12/datatables.min.js"></script>--}}
    <script src="{{asset('/assets/bundles/datatablescripts.bundle.js')}}"></script>
    <script src="{{asset('/assets/bundles/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('/assets/bundles/buttons.bootstrap4.min.js')}}"></script>
    <script src="{{asset('/assets/bundles/buttons.colVis.min.js')}}"></script>
    <script src="{{asset('/assets/bundles/buttons.html5.min.js')}}"></script>
    <script src="{{asset('/assets/bundles/buttons.print.min.js')}}"></script>
    <script src="{{asset('/assets/bundles/bundles/mainscripts.bundle.js')}}"></script>
    <script src="{{asset('/assets/bundles/jquery-datatable.js')}}"></script>
    <script src="{{asset('/js/sweetalert.min.js')}}"></script>

    @include('sweet::alert')
    <script>
        $(document).on("click", "#delete", function () {
            let id = $(this).attr('data-id');
            swal({
                title: "آیا از حذف دسته بندی مطمئن هستید؟",
                text: "بعد از حذف دسته بندی دیگر دسترسی به رنگ نخواهید داشت!",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            }).then((willDelete) => {
                if (willDelete) {
                    $.ajax({
                        async: false,
                        type: "POST",
                        url: '{{ route('deleteCat.ajax') }}',
                        data: {
                            id: id,
                            "_token": "{{ csrf_token() }}"
                        },
                        success: function (result) {
                            swal("دسته بندی مورد نظر شما با موفقیت حذف شده است!!", {
                                icon: "success",
                            });
                            window.location.reload();
                        }
                    });
                } else {
                    swal("از حذف دسته بندی منصرف شده اید");
                }
            });



        });
    </script>
    <script>
        $(function () {
           $("#table").DataTable();
            $( "#tablecontents" ).sortable({
                items: "tr",
                cursor: 'move',
                opacity: 0.6,
                update: function() {
                    sendOrderToServer();
                }
            });

            function sendOrderToServer() {

                var order = [];
                $('tr.row1').each(function(index,element) {
                    order.push({
                        id: $(this).attr('data-id'),
                        position: index+1
                    });
                });

                $.ajax({
                    type: "POST",
                    dataType: "json",
                    url: "{{ url('sort') }}",
                    data: {
                        order:order,
                        _token: '{{csrf_token()}}'
                    },
                    success: function(response) {
                        console.log(response);

                    }
                });

            }
        });
    </script>
@endsection

resources/views/Admin/category/subCategory.blade.php
@extends('Admin.master')

@section('style')
    <link rel="stylesheet" href="{{asset('/assets/vendor/sweetalert/sweetalert.css')}}">
@endsection
@section('content')
    <div class="container-fluid">
        <div class="block-header">
            <div class="row clearfix">
                <div class="col-md-6 col-sm-12">
                    <h1>زیر دسته ها</h1>
                </div>
                <div class="col-md-6 col-sm-12 text-right hidden-xs">
                    <a href="{{ route('categories.create') }}" class="btn btn-sm btn-primary" title="">ایجاد دسته بندی</a>
                </div>
            </div>
        </div>

        <div class="row clearfix">
            <div class="col-lg-12">
                <div class="card">
                    <div class="header">
                        <h2>زیر دسته</h2>
                        <input type="hidden" value="{{ $category->id }}" class="catId">
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-hover js-basic-example dataTable table-custom spacing5" id="table">
                                <thead>
                                <tr>
                                    <th>ردیف</th>
                                    <th>نام</th>
                                    <th>آیکن</th>
                                    <th>رنگ</th>
                                    <th>عکس</th>
                                    <th>sort</th>
                                    <th>عملیات</th>
                                </tr>
                                </thead>
                                <tbody id="tablecontents">
                                @forelse ($subCategories as $index=>$value)

                                    <tr class="row1" data-id="{{ $value->id }}">
                                        <td>{{$index + 1}}</td>
                                        <td>{{$value->name}}</td>
                                        <td>{{$value->icon}}</td>
                                        <td>{{$value->color}}</td>
                                        <td>
                                            <img src="{{$value->img}}" class="img-fluid" width="100" height="100"/>
                                        </td>
                                        <td>{{$value->sort_order}}</td>
                                        <td>
                                            <button type="button" data-id="{{ $value->id }}" id="delete" class="btn btn-sm btn-danger" title="" data-toggle="tooltip" data-placement="top" data-original-title="حذف دسته بندی"><i class="icon-trash"></i></button>
                                            <a href="{{ route('categories.edit' , $value->id) }}" class="btn btn-sm btn-info" title="" data-toggle="tooltip" data-placement="top" data-original-title="ویرایش دسته بندی"><i class="icon-pencil"></i></a>
                                            <a href="{{ route('categories.show' , $value->id) }}" class="btn btn-sm btn-light" title="" data-toggle="tooltip" data-placement="top" data-original-title="نمایش دسته بندی"><i class="icon-eye"></i></a>
                                        </td>
                                    </tr>
                                @empty
                                    <p>No subCategories</p>
                                @endforelse
                                </tbody>
                            </table>
                            <h5>Refresh <button class="btn btn-default" onclick="window.location.reload()"><b>REFRESH</b></button></h5>

                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection

@section('script')
    {{--<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>--}}
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    {{--<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.12/datatables.min.js"></script>--}}
    <script src="{{asset('/assets/bundles/datatablescripts.bundle.js')}}"></script>
    <script src="{{asset('/assets/bundles/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('/assets/bundles/buttons.bootstrap4.min.js')}}"></script>
    <script src="{{asset('/assets/bundles/buttons.colVis.min.js')}}"></script>
    <script src="{{asset('/assets/bundles/buttons.html5.min.js')}}"></script>
    <script src="{{asset('/assets/bundles/buttons.print.min.js')}}"></script>
    <script src="{{asset('/assets/bundles/bundles/mainscripts.bundle.js')}}"></script>
    <script src="{{asset('/assets/bundles/jquery-datatable.js')}}"></script>
    <script src="{{asset('/js/sweetalert.min.js')}}"></script>

    @include('sweet::alert')
    <script>
        $(document).on("click", "#delete", function () {
            let id = $(this).attr('data-id');
            swal({
                title: "آیا از حذف دسته بندی مطمئن هستید؟",
                text: "بعد از حذف دسته بندی دیگر دسترسی به رنگ نخواهید داشت!",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            }).then((willDelete) => {
                if (willDelete) {
                    $.ajax({
                        async: false,
                        type: "POST",
                        url: '',
                        data: {
                            id: id,
                            "_token": "{{ csrf_token() }}"
                        },
                        success: function (result) {
                            swal("دسته بندی مورد نظر شما با موفقیت حذف شده است!!", {
                                icon: "success",
                            });
                            window.location.reload();
                        }
                    });
                } else {
                    swal("از حذف دسته بندی منصرف شده اید");
                }
            });



        });
    </script>
    <script>
        $(function () {
           $("#table").DataTable();
            $( "#tablecontents" ).sortable({
                items: "tr",
                cursor: 'move',
                opacity: 0.6,
                update: function() {
                    sendOrderToServer();
                }
            });

            function sendOrderToServer() {

                var order = [];
                $('tr.row1').each(function(index,element) {
                    order.push({
                        id: $(this).attr('data-id'),
                        position: index+1
                    });
                });
                let catId = $('.catId').val();
                //console.log(catId);
                $.ajax({
                    type: "POST",
                    dataType: "json",
                    url: "{{ url('sortSubCategory') }}",
                    data: {
                        order:order,
                        catId:catId,
                        _token: '{{csrf_token()}}'
                    },
                    success: function(response) {
                        console.log(response);

                    }
                });

            }
        });
    </script>
@endsection